#!/bin/bash

#Add Git PPA
if (which apt-get>/dev/null); then
    sudo add-apt-repository ppa:git-core/ppa -y
    sudo apt update -y
    sudo apt install git keychain -y
elif (which pacman>/dev/null); then
    pacman -Sy git keychain
fi

#Remove symlinks
rm -f ~/.gitconfig

#Create symlink
ln -s ~/dotfiles/git/.gitconfig ~/.gitconfig
