#!/bin/bash

#Add Git PPA
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt update -y
sudo apt install git keychain -y

#Remove symlinks
rm -f ~/.gitconfig

#Create symlink
ln -s ~/dotfiles/git/.gitconfig ~/.gitconfig
