#!/bin/bash

#Update Packages & Install Zsh and Plugins
if (which apt-get>/dev/null); then
    sudo apt-get update -y
    sudo apt-get upgrade -y
    sudo apt-get install zsh zsh-syntax-highlighting zsh-autosuggestions keychain -y
elif (which pacman>/dev/null); then
    sudo pacman -Sy zsh zsh-syntax-highlighting zsh-autosuggestions keychain
fi

chsh -s /usr/bin/zsh

#Install powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/dotfiles/zsh/powerlevel10k

#Remove existing symlinks
rm -f ~/.zshrc
rm -f ~/.p10k.zsh

#Create symlinks
ln -s ~/dotfiles/zsh/.zshrc ~/.zshrc
ln -s ~/dotfiles/zsh/.p10k.zsh ~/.p10k.zsh
